Repository UBC-MDS/feature-selection-python, pull requests merged in 2020-03, with the labels that each got.

#20 added ecosystem to README
  README.md
Labels: documentation

#31 Implement RFE
  feature_selection/RecursiveFeatureElimination.py
  feature_selection/__init__.py
  feature_selection/recursive_feature_elimination.py
  poetry.lock
  pyproject.toml
  tests/test_RecursiveFetaureElimination.py
Labels: enhancement

#33 Add simulated annealing feature selector
  feature_selection/__init__.py
  feature_selection/simulated_annealing.py
  tests/test_simulated_annealing.py
Labels: enhancement

#32 Update forward selection function
  README.md
  feature_selection/ForwardSelect.py
  feature_selection/__init__.py
  feature_selection/forward_selection.py
  tests/test_forward_selection.py
Labels: enhancement

#42 fix test to be more likely of passing
  tests/test_simulated_annealing.py
Labels: bug

#58 add dependencies to README
  README.md
Labels: documentation

#60 fix pep-8 format issues
  feature_selection/forward_selection.py
  feature_selection/simulated_annealing.py
  tests/test_forward_selection.py
  tests/test_simulated_annealing.py
Labels: bug

#82 Fix test for n_features_to_select
  feature_selection/recursive_feature_elimination.py
  tests/test_recursive_fetaure_elimination.py
Labels: bug

#87 Update Usage Documentation
  README.md
  docs/usage.rst
Labels: documentation

#88 Minor document fixes
  .github/workflows/release.yml
  docs/usage.rst
  feature_selection/__init__.py
Labels: documentation

#99 add random_state to sim_anneal
  feature_selection/simulated_annealing.py
Labels: enhancement
